### ISSUE TITLE
R1 - How to install new heatbed for replacement 

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#102]
Also add in glueing magnets onto bed

**Comment by mnacinopa** [comment]
Will the new replacement heatbeds be the new removable version?

**Comment by CobyKabili** [comment]
1. We need a side note of old version of heat bed needs to remove the ribbon cable mount on the y axis bracket.

2. Side note of new bed, make sure it's plugged into its plug out of the back of the printer.
