### ISSUE TITLE
Changing start gcode via web dashboard for different starting temps

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#107]
We have had a lot of customers call in about there temps not being set to the right temperature, even though this is just the starting priming line. We need a tutorial on how to go into the web dashboard and change the start gcode temps, and possibly other items in there as well.

**Comment by mnacinopa** [comment]
@peries  Can you scrub through this? Also need to think of a better title/where to place this article
[Changing the Start temp](https://help.robo3d.com/hc/en-us/articles/115002558532)

**Comment by peries** [comment]
@mnacinopa edited

**Comment by mnacinopa** [comment]
@CobyKabili 
[R1+ RAMPS Board Wiring Diagram](https://robo3d.zendesk.com/hc/en-us/articles/115002569971)

**Comment by peries** [comment]
should we also add it as an attachment so people can download it to see it bigger?

**Comment by mnacinopa** [comment]
Thats a good idea. I'll do it.

**Comment by mnacinopa** [comment]
@peries  Should be updated.

**Comment by peries** [comment]
cool.

I just noticed it looks like there's an extra grey line going over the z motor connector on the board
<img width="275" alt="screen shot 2017-11-03 at 2 27 12 pm" src="https://user-images.githubusercontent.com/24902256/32396606-2204508c-c0a3-11e7-8818-e23ff64a0e50.png">

**Comment by mnacinopa** [comment]
@peries  [Fixed. ](https://help.robo3d.com/hc/en-us/articles/115002569971)

**Comment by CobyKabili** [comment]
https://help.robo3d.com/hc/en-us/articles/115002558532-Changing-the-starting-printing-temperature-via-the-start-gcode
