### ISSUE TITLE
How to do PID tuning on R2/C2

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#108]
Need to write up guide on how to PID tune your printer. We should also include a gcode file that users can easily print to do it for them if they dont want to use the terminal

**Comment by mnacinopa** [comment]
[First Pass](https://help.robo3d.com/hc/en-us/articles/115002627252-How-to-PID-Tune-your-Printer)
@peries @CobyKabili  Take a look at it when you can
