### ISSUE TITLE
R1+ Calibrating Z Axis Guide

### ISSUE THREAD

**Issue by mnacinopa** [Robo3D/support.robo3d.com#114]
Spinning lead screws until the Endstops disengage. 

Update it

**Comment by mnacinopa** [comment]
https://help.robo3d.com/hc/en-us/articles/115002626312

**Comment by CobyKabili** [comment]
We need to have one more instruction saying the raise the extruder up and a gif showing moving the extruder from left to right making sure it is flat across the bed meaning no change in gap between the left and right side.

**Comment by mnacinopa** [comment]
[Updated it](https://robo3d.zendesk.com/knowledge/articles/115002626312/en-us?brand_id=114094254812&return_to=%2Fhc%2Fen-us%2Farticles%2F115002626312)
@CobyKabili  Let me know if this works

**Comment by CobyKabili** [comment]
cool. Edited it a bit but looks good to close out.
