### ISSUE TITLE
Add R1+ videos into support docs

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#123]
@mnacinopa I made these a while ago but would be nice to get them into the support docs where they need to go.

https://drive.google.com/open?id=1-JP2pLX-iC3hcNdhWB3wOtoy-n9joe2W

**Comment by mnacinopa** [comment]
@CobyKabili  These are awesome.I'll find a place for them

**Comment by mnacinopa** [comment]
@CobyKabili @peries 

Added all three to the help docs:

[Removing Jammed filament with tweezzers](https://help.robo3d.com/hc/en-us/articles/115000723592)

[R1+ Hotend Removal](https://help.robo3d.com/hc/en-us/articles/115000716831-R1-Plus-Quick-Release)

[Loading Filament](https://help.robo3d.com/hc/en-us/articles/115001259352-Loading-filament)
