### ISSUE TITLE
Operation - how to use onboard slicer

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#16]
Explain how to use onboard slicer

@Ximidar are we changing the way the onboard slicer works or are we keeping it through the wizards for now?

**Comment by Ximidar** [comment]
The last I heard we were keeping it the same for now. It's going to take an entire redesign and recode to make it apart of the file system. So it may change, just not for the foreseeable future

**Comment by CobyKabili** [comment]
Ok thanks. I will use the workflow that is in there now
