### ISSUE TITLE
Headers needed for R2

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#37]
@bkabili I need these headers to be made before we push the doc live

- [x] Getting Started

- [x] Operation

- [x] Maintenance

- [x] Troubleshooting

Also need Simple headers that just show the product;

- [x] R2

- [x] C2

**Comment by CobyKabili** [comment]
Here are the renders https://www.dropbox.com/home/R2%20renders

**Comment by bkabili** [comment]
![c2](https://cloud.githubusercontent.com/assets/5116731/26738572/daf8c8ca-478b-11e7-8eb9-8519f736668a.jpg)
![r2-getting-started](https://cloud.githubusercontent.com/assets/5116731/26738573/dafb52c0-478b-11e7-8fcc-05ac197d8b03.jpg)
![r2-maintenance](https://cloud.githubusercontent.com/assets/5116731/26738571/daf88ba8-478b-11e7-834e-a39db85b2a8c.jpg)
![r2-operation](https://cloud.githubusercontent.com/assets/5116731/26738570/daf8159c-478b-11e7-8e80-33e3c685d5d6.jpg)
![r2-troubleshooting](https://cloud.githubusercontent.com/assets/5116731/26738574/db095d34-478b-11e7-8776-8a2d4d65ae33.jpg)
![r2](https://cloud.githubusercontent.com/assets/5116731/26738575/db0f62f6-478b-11e7-9d67-8f33443bd6e1.jpg)

**Comment by CobyKabili** [comment]
Thanks @bkabili the Robo R2 maintenance is a picture of the C2 though...

**Comment by bkabili** [comment]
@CobyKabili ok, lets just use this then.
![r2-maintenance](https://cloud.githubusercontent.com/assets/5116731/26739276/700621fe-478e-11e7-9720-581134c3b58b.jpg)

**Comment by CobyKabili** [comment]
Awesome thanks!
