### ISSUE TITLE
operation - R2- starting the webcam

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#38]
User is confused as to how to start the webcam. Didnt know it ships with it off - need to show how to turn it on.

**Comment by CobyKabili** [comment]
@Ximidar is this in the latest release? By latest release I mean its pushed to customers. Is there any special instructions beside toggling it on and off from the screen?

**Comment by Ximidar** [comment]
@CobyKabili There is only a toggle on the LCD screen. I believed it was pushed to the users, but we will need @victorevector to verify. There is no other information on turning the webcam on and off

**Comment by CobyKabili** [comment]
@Ximidar @victorevector what is the function that this button does? (I assume its just starting the webcam) Does the user need to refresh the browser once it is pressed?

**Comment by victorevector** [comment]
@CobyKabili there are currently 3 official ways to turn the webcam on and off:

1. RoboLCD: Utilities > Options > Webcam

2. Web Dashboard: Top Right Menu > System > Start Webcam; then refresh the page

3. iOS (BETA only; release Friday): Webcam > toggle button
