### ISSUE TITLE
Make a 'latest' page that has both C2 AND R2 information

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#39]
Right now, the latest page is the first thing that comes up, but there is only info on the C2. We need to change this to be both products.

http://docs.robo3d.com/en/latest/index.html

@bkabili can you make a header that show both c2 and r2 and maybe the app and a comp with cura on it? Anything that looks good in your opinion to be the header for all documentation

**Comment by bkabili** [comment]
@CobyKabili How about this?
![support](https://cloud.githubusercontent.com/assets/5116731/26745922/2a3603b2-47aa-11e7-9478-245595fa4737.jpg)

**Comment by CobyKabili** [comment]
@bkabili Can it say docs instead of support

**Comment by bkabili** [comment]
@CobyKabili 
![docs](https://cloud.githubusercontent.com/assets/5116731/26795274/556dfc80-49e2-11e7-8c5b-1c098b2e057f.jpg)

**Comment by CobyKabili** [comment]
perfect
