### ISSUE TITLE
operation - shut down procedure

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#56]

**Comment by mnacinopa** [comment]
Added to Helpdesk articles [Correct Shutdown Sequence](https://help.robo3d.com/hc/en-us/articles/115001490471-Correct-Shutdown-Sequence)

**Comment by peries** [comment]
@mnacinopa a few edits:
Make sure to follow the proper **shut down** procedure to help keep your machine running smoothly. **Do not turn off the back power switch before running the on-screen shut down  sequence.**

**On the printer's touchscreen, navigate** to Options >> System >> Shut Down
Follow **the** on-screen instructions and wait **until** the screen turns black.
Once the screen turns black, shut off the printer using the **power** switch located on the back of **the printer.**

**Comment by mnacinopa** [comment]
@peries  Got it. Updated
