### ISSUE TITLE
Ads are showing up below side menu

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/support.robo3d.com#72]
![screen shot 2017-07-17 at 5 21 08 pm](https://user-images.githubusercontent.com/4200307/28295261-59b4bc5e-6b14-11e7-8206-138e83a7d266.png)

**Comment by bkabili** [comment]
@AllenMcAfee 
Looks like they ask for a donation to remove the ads.
https://readthedocs.org/dashboard/support-site/advertising/

They ask for at least $5/month which we can pay with a credit card here:
https://readthedocs.org/accounts/gold/subscription/?

I can always hide that div until we decide what to do as well...

**Comment by CobyKabili** [comment]
@bkabili hide it for now

**Comment by bkabili** [comment]
That div is now hidden, let me know it looks good on your end.
