### ISSUE TITLE
Mobile view shows `Stashed changes` header in menu

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/support.robo3d.com#73]
![img_0387](https://user-images.githubusercontent.com/4200307/28642259-a6ab4066-7206-11e7-94de-9eb23ce3f53e.PNG)

**Comment by CobyKabili** [comment]
@bkabili this is weird ive never seen that. Maybe because there is more content then we are showing? I dont know how to fix this

**Comment by bkabili** [comment]
@AllenMcAfee @CobyKabili I noticed when you refresh the page on a desktop browser you can see this same message flash quickly and then go away. Ill look in to this.

**Comment by bkabili** [comment]
@AllenMcAfee this is from a git merge conflict:
https://wincent.com/wiki/Git_merge_conflict_cheatsheet

Coby said you would know best how to resolve something like this.

**Comment by AllenMcAfee** [comment]
This can be a GitHub merge error. There is really no way to reverse this
that I know of, you'll need to scrub these bugged lines by hand.

**Comment by CobyKabili** [comment]
this is outdated for the moment. Can be reopened if we decide to use it for other projects
