### ISSUE TITLE
Extruder jammed tutorial has incorrect mapping of extruder wires

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/support.robo3d.com#78]
![screen shot 2017-08-11 at 4 13 04 pm](https://user-images.githubusercontent.com/4200307/29235014-22105416-7eb0-11e7-9e1b-93cba67b80d8.png)

The above image has the Heater 1 OUT connector labeled as Therm.  The connector labeled Heater is supposed to read Heater 1 IN.

**Comment by mnacinopa** [comment]
Fixed the labeling
