### ISSUE TITLE
Add instructions on how to download Octoprint log files for CS

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/support.robo3d.com#81]
![screen shot 2017-08-16 at 5 31 12 pm](https://user-images.githubusercontent.com/4200307/29390982-c8f981fc-82a8-11e7-9f6a-c9920e697068.png)

The image above shows the location of the Logs within the settings screen of Octoprint.  The three logs highlighted are the logs customers should download and send the CS rep helping them.  The logs are timestamped, so we will need to make sure we explain that only the most recent logs are needed.

**Comment by mnacinopa** [comment]
Coby just asked me to make documentation for the Webdash. I'll try to get this done this week.

**Comment by mnacinopa** [comment]
This is done. 
http://support-site.readthedocs.io/en/dev/web-interface/index.html
