### ISSUE TITLE
Tutorial for checking health of pogo pins, checking if your bed is seated properly

### ISSUE THREAD

**Issue by jerryrobo3d** [Robo3D/support.robo3d.com#82]
I know we have a pogo pin replacement tutorial but it doesn't tell you how to check if you need to replace your pogo pins. Something along these lines is needed...

"Please pull off your bed and check the 6 golden colored pins in the back that are vertical.  Each one should be springy and rebound when you press down on them.  Let me know if any of them are not springy."

Also to make sure the customer's bed is seated down well...
"Make sure your heat bed is seated down correctly and evenly.  if you press on any one of the corners of your heat bed, it should not rock."

**Comment by mnacinopa** [comment]
Just added a pogo pin check. 
[Pogo Pin Check](
http://support-site.readthedocs.io/en/dev/R2/Troubleshooting/index.html#checking-your-pogo-pins)
