### ISSUE TITLE
Request tutorial for unclogging extruder

### ISSUE THREAD

**Issue by davidmanley** [Robo3D/support.robo3d.com#84]
need detailed guide for un clogging the R2 hotend

**Comment by mnacinopa** [comment]
@CobyKabili @peries 

I updated the old [Clogged Extruder guide](https://help.robo3d.com/hc/en-us/articles/115000715531) because it did not seem very useful.  If you think its complete/ after you make edits I can copy it over to the C2  help docs.

**Comment by CobyKabili** [comment]
@mnacinopa steps are missing 2-3. It's acting up again

**Comment by mnacinopa** [comment]
Should be fixed. Added it to the C2 side as well.
