### ISSUE TITLE
How to swap out micro sd on R2/C2 

### ISSUE THREAD

**Issue by spoogs2003** [Robo3D/support.robo3d.com#85]
Please create a tutorial on how to replace a micro sd card on the raspberry pi.

**Comment by CobyKabili** [comment]
@mnacinopa can you please make these? We can reuse some content from opening up the printers to get to the inside if you would like.

**Comment by mnacinopa** [comment]
This is done. I chose to not open up the Front Panel for the R2 Micro SD swap because it's not entirely necessary. It's more work removing that, than simply fiddling with the SD card a little bit to get the right angle to reinsert it.  Done for R2 and C2 in their respective Troubleshooting sections
