### ISSUE TITLE
How to swap bearings on X and Y axis on the R2/C2 extruder mount

### ISSUE THREAD

**Issue by spoogs2003** [Robo3D/support.robo3d.com#86]
A tutorial on how to swap out bearings

**Comment by CobyKabili** [comment]
@ROBOLabs do you have this?

**Comment by ROBOLabs** [comment]
It's in the pipeline. Right now I have the Gantry Removal Guide, the Front Panel Removal Guide, and the LCD Screen Removal Guide. Next in line is the Z-axis Removal Guide and the Extruder Removal Guide, so I'll add a demonstration of how to swap bearings in that one.

**Comment by CobyKabili** [comment]
https://help.robo3d.com/hc/en-us/articles/115001633792-Servicing-Extruder-Assembly
