### ISSUE TITLE
Gantry alignment on R2 and C2

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#90]
Tutorial showing how to loosen and tighten pulleys on R2 and C2 for fixing spacing (maybe the creeking noise) - dont forget to use the rod holders for keeping the gantry alligned. May need to put these up on thingiverse for users to print before they start the tutorial.

**Comment by mnacinopa** [comment]
[Gantry Alignment](https://help.robo3d.com/hc/en-us/articles/115001792512). Here's a rough pass at a gantry aligning tutorial.

**Comment by mnacinopa** [comment]
@CobyKabili  Revised it! Let me know if you want it done any differently.

**Comment by CobyKabili** [comment]
still not quit right. Ill let you know, but its almost there.

**Comment by CobyKabili** [comment]
@mnacinopa all 4 pulleys of one axis have to be loosened. Also, if there can be a picture highlighting which pulleys to loosen it would be nice.

**Comment by CobyKabili** [comment]
@peries can you review these and make sure they make sense to you

**Comment by mnacinopa** [comment]
@CobyKabili  I added the picture highlighting the pulleys into the R2 article

**Comment by peries** [comment]
@CobyKabili made a couple tiny edits but it looks good to me

**Comment by CobyKabili** [comment]
@mnacinopa can you copy this to the C2 page and just put a note that it is the same process. Then you can close out this issue.

**Comment by mnacinopa** [comment]
@CobyKabili @peries  

[Its liveee. ](https://help.robo3d.com/hc/en-us/articles/115002529251?flash_digest=6e45df654650a65417329aaba7b78704720b4caa)
