### ISSUE TITLE
Troubleshooting - R1 - check the wire for bad extruder motor and how to replace it

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#91]
check stepper driver as well

**Comment by mnacinopa** [comment]
@CobyKabili  Can you show me how to troubleshoot this at some point?

**Comment by mnacinopa** [comment]
@CobyKabili  I Created the troubleshooting portion of the issue. Published it as a draft. Next I'll work on actual replacement of the parts.

**Comment by mnacinopa** [comment]
@CobyKabili @peries   Finished updating it for replacing the stepper driver. Please review/edit grammar as you see fit and go ahead and publish it. 
[Extruder Motor Not Working](https://help.robo3d.com/hc/en-us/articles/115002197612)

**Comment by CobyKabili** [comment]
@mnacinopa I don't see steps 5-8 for some reason...

**Comment by mnacinopa** [comment]
@CobyKabili  Weird. It deleted them.

oh well I remade the steps.

**Comment by CobyKabili** [comment]
@mnacinopa this looks great! I edited the last version and pushed it live. Good work, this was a big one we will use a lot.
