### ISSUE TITLE
Electronics mainboard images and plug locations for R2/C2 and R1+

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#96]
@mnacinopa we need a schematic of the electronics boards for when customers are replacing and plugging in. Something like the 3 examples below, but we need it for both the all 3 of our printers

http://reprap.org/mediawiki/images/thumb/6/6d/Rampswire14.svg/500px-Rampswire14.svg.png

http://www.hobbyist.co.nz/sites/default/files/ramps/schematic.png

http://www.achatzmediaserver.com/support/wp-content/uploads/2015/11/ramps-14-instructions-connections-3d-printer.png

**Comment by mnacinopa** [comment]
@AllenMcAfee  We want to do something like what Coby linked to above.

**Comment by mnacinopa** [comment]
@CobyKabili  [R2/C2 Mainboard Schematic](https://help.robo3d.com/hc/en-us/articles/115002394151)

**Comment by mnacinopa** [comment]
@CobyKabili  
Here's the first draft of it. I asked @peries to try to see if she could clean it up a bit. 
![artboard 1](https://user-images.githubusercontent.com/25697446/32194346-5c84f9b6-bd77-11e7-98b2-51a7614195a2.png)

The C2 one would obviously just be this without the heatbed connections
![artboard 1](https://user-images.githubusercontent.com/25697446/32194783-9b8f2432-bd78-11e7-97b3-e2937a344c15.png)

**Comment by mnacinopa** [comment]
Doubled the thickness of the wiring to make it easier to see
**R2**
![artboard 1](https://user-images.githubusercontent.com/25697446/32195709-5279914e-bd7b-11e7-9fe1-2a7f1f58d143.png)

**C2**
![artboard 1](https://user-images.githubusercontent.com/25697446/32195728-6173a3e2-bd7b-11e7-8cc7-541f5ed7b563.png)

**Comment by CobyKabili** [comment]
@mnacinopa these are great. One question, is there a reason the board is upside down?

**Comment by AllenMcAfee** [comment]
@mnacinopa the "B" is flipped in this version as well.  Who the hell is ropo?

**Comment by mnacinopa** [comment]
@CobyKabili  Not really. I made the board first then made the logo after and didnt think about it. 

@AllenMcAfee  Some new printer company thats trying to steal our logo. 

Wiring Edits Peri made.  Changed ropo to robo, for copyright reasons. 

C2
![artboard 1](https://user-images.githubusercontent.com/25697446/32234541-5692cbf2-be1a-11e7-8281-58d97ec28de0.png)

R2
![artboard 1](https://user-images.githubusercontent.com/25697446/32234548-5bf1d4e4-be1a-11e7-8507-b252e5507204.png)

**Comment by CobyKabili** [comment]
@mnacinopa we need an R1+ diagram as well. Our ramps boards are a little different than the stock off the shelf ones

**Comment by mnacinopa** [comment]
![web 1920 1](https://user-images.githubusercontent.com/25697446/32387006-556b667c-c080-11e7-9cc6-0521cd96a158.png)

**Comment by CobyKabili** [comment]
looks good. Put it in an article and I can update a macro for it.

**Comment by mnacinopa** [comment]
@CobyKabili 
[R1+ RAMPS Board Wiring Diagram](https://robo3d.zendesk.com/hc/en-us/articles/115002569971)
Posted in the wrong issue. Lols

**Comment by CobyKabili** [comment]
Perfect. Thank you.
