### ISSUE TITLE
How to change hotend while using old therm and heater core R2/C2

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#97]

**Comment by CobyKabili** [comment]
Need article explaining steps to do this

**Comment by mnacinopa** [comment]
@CobyKabili  i finished the articles for both the C2 and R2. I also updated the Removing the Hotend articles for both. Let me know what you think.

**Comment by CobyKabili** [comment]
Awesome! Edited them a tiny bit but looks great
