### ISSUE TITLE
Update C2 screen article for ribbon cable placement

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/support.robo3d.com#98]
Need to update screen ribbon cable article to show exactly how to plug back in. Customers are plugging into the wrong pins and some are making the screen go out.

**Comment by mnacinopa** [comment]
@CobyKabili  I wanted to do this but people have varying versions of C2 Screens. Which is why I mentioned in the article to "Plug it in exactly as you found it". One would require inverting the connector, and one would not.
